# See full list of defaults here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# To see all cops used see here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Include:
      - Rakefile
      - Gemfile

LineLength:
  Max: 120

Style/CaseIndentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - '**/*spec_helper.rb'
