source 'https://rubygems.org'

ruby '>=2.6.8'

gem 'capybara-screenshot', git: 'https://github.com/mattheworiordan/capybara-screenshot.git'
gem 'factory_bot'
gem 'howitzer', git: 'https://github.com/strongqa/howitzer.git', branch: 'master'
gem 'matrix'
gem 'multi_json'
gem 'pry'
gem 'pry-byebug'
gem 'repeater'
gem 'rest-client'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'spyke'
